version: "3.3"

networks:
  swarm_net:
    external: true

services:
  cleaner:
    image: prometheus_cleaner
    networks:
      - swarm_net
    deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.1"
            memory: '50M'
        placement: 
            constraints: [node.role != manager]
    labels:
      org.label-schema.group: "prometheus_cleaner"

  